### ISSUE TITLE
Usage for two point sets of different sizes

### ISSUE THREAD

**Issue by idocohn** [ClayFlannigan/icp#5]
In the code it seems like you assume (and assert) that the two point sets you get are of the same shape (Nxm)

In our use case we try to register two point clouds from successive revolutions.
We will probably not have the same number of points.

Why do you have this requirement? If it's for the NN stage then it seems not relevant.
Is there a way to extend your code to support our case?

**Comment by ClayFlannigan** [comment]
This implementation does require point sets to be the same shape.  Typically, one would sample the point sets to enforce this constraint (and sometimes to speed it up).  There are probably several methods you might use to sample the points.  Try reviewing [this](https://www.cs.princeton.edu/~smr/papers/fasticp/fasticp_3dim01.ppt
) for some inspiration.

**Comment by idocohn** [comment]
Thanks, that makes sense.

**Comment by abhineet99** [comment]
@idocohn  I have a similar case of successive revolutions. But then some of the points in a point cloud can not be mapped to any other point in the other cloud right? Like some points might not be visible through an angle. How did ICP perform in your case then? I'm not getting great results.

**Comment by BoltonBailey** [comment]
I'll just note here that I was able to comment out the assert lines and have it work fine.

**Comment by ynma-hanvo** [comment]
> @idocohn I have a similar case of successive revolutions. But then some of the points in a point cloud can not be mapped to any other point in the other cloud right? Like some points might not be visible through an angle. How did ICP perform in your case then? I'm not getting great results.

I am doing the same thing as you did.  can you share your result on this case,   is it working fine?
