### ISSUE TITLE
It seems that the calculation of rotation matrix have a mistake?

### ISSUE THREAD

**Issue by 446810140** [ClayFlannigan/icp#6]
Dear Clay Flannigan,
According to equation 16 in the paper "Least-squares Rigid Motion Using SVD" ( http://igl.ethz.ch/projects/ARAP/svd_rot.pdf ), it seems that H should be equal to np.dot(AA, BB.T) in icp.py?

**Comment by 446810140** [comment]
Hmm, I understand it. Matrix A and B have been transposed when input, so it is right.
Thanks & Best Regards!

**Comment by yanghtr** [comment]
@446810140 
Hello, I am a little confused.
In the function: best_fit_transform(A, B), is A the src? Is B the dst? which means:
B = (A+t) R
Is it correct? 
Thank you very much!
